// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/thanhpp/prom/pkg/ccmanrpc/entity.proto

package entity

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timerpc "github.com/thanhpp/prom/pkg/timerpc"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// card
type Card struct {
	ID          uint32        `protobuf:"varint,1,opt,name=ID,proto3" json:"id" gorm:"Column:id; Type:int; primaryKey"`
	Title       string        `protobuf:"bytes,2,opt,name=Title,proto3" json:"title" gorm:"Column:title; Type:text"`
	Description string        `protobuf:"bytes,3,opt,name=Description,proto3" json:"description" gorm:"Column:description; Type:text"`
	ColumnID    uint32        `protobuf:"varint,4,opt,name=ColumnID,proto3" json:"column_id" gorm:"Column:column_id; Type:bigint"`
	AssignedTo  uint32        `protobuf:"varint,5,opt,name=AssignedTo,proto3" json:"assigned_to" gorm:"Column:assigned_to; Type:bigint"`
	CreatedBy   uint32        `protobuf:"varint,6,opt,name=CreatedBy,proto3" json:"created_by" gorm:"Column:created_by; Type:bigint"`
	DueDate     *timerpc.Time `protobuf:"bytes,7,opt,name=DueDate,proto3" json:"due_date" gorm:"Column:due_date"`
	CreatedAt   *timerpc.Time `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"created_at" gorm:"Column:created_at"`
	UpdatedAt   *timerpc.Time `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"updated_at" gorm:"Column:updated_at"`
	DeletedAt   *timerpc.Time `protobuf:"bytes,10,opt,name=DeletedAt,proto3" json:"deleted_at" gorm:"Column:deleted_at"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_bae371cadf442b09, []int{0}
}
func (m *Card) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Card.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return m.Size()
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Card) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Card) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Card) GetColumnID() uint32 {
	if m != nil {
		return m.ColumnID
	}
	return 0
}

func (m *Card) GetAssignedTo() uint32 {
	if m != nil {
		return m.AssignedTo
	}
	return 0
}

func (m *Card) GetCreatedBy() uint32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Card) GetDueDate() *timerpc.Time {
	if m != nil {
		return m.DueDate
	}
	return nil
}

func (m *Card) GetCreatedAt() *timerpc.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Card) GetUpdatedAt() *timerpc.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Card) GetDeletedAt() *timerpc.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

// column
type Column struct {
	ID        uint32        `protobuf:"varint,1,opt,name=ID,proto3" json:"id" gorm:"Column:id; Type:int; primaryKey; autoIncrement"`
	Title     string        `protobuf:"bytes,2,opt,name=Title,proto3" json:"title" gorm:"Column:title; Type:text"`
	ProjectID uint32        `protobuf:"varint,3,opt,name=ProjectID,proto3" json:"project_id" gorm:"Column:project_id; Type:bigint"`
	Cards     []*Card       `protobuf:"bytes,4,rep,name=Cards,proto3" json:"cards" gorm:"foreignKey:ColumnID; references:ID"`
	CreatedBy uint32        `protobuf:"varint,5,opt,name=CreatedBy,proto3" json:"created_by" gorm:"Column:created_by; Type:bigint"`
	CreatedAt *timerpc.Time `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"created_at" gorm:"Column:created_at"`
	UpdatedAt *timerpc.Time `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"updated_at" gorm:"Column:updated_at"`
	DeletedAt *timerpc.Time `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"deleted_at" gorm:"Column:deleted_at"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_bae371cadf442b09, []int{1}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Column.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return m.Size()
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Column) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Column) GetProjectID() uint32 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *Column) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *Column) GetCreatedBy() uint32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Column) GetCreatedAt() *timerpc.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Column) GetUpdatedAt() *timerpc.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Column) GetDeletedAt() *timerpc.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Card)(nil), "ccmanmodel.Card")
	proto.RegisterType((*Column)(nil), "ccmanmodel.Column")
}

func init() {
	proto.RegisterFile("github.com/thanhpp/prom/pkg/ccmanrpc/entity.proto", fileDescriptor_bae371cadf442b09)
}

var fileDescriptor_bae371cadf442b09 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x31, 0x6f, 0xd3, 0x4c,
	0x18, 0xc7, 0xe3, 0xb4, 0x49, 0x93, 0x8b, 0x2a, 0xbd, 0xf2, 0xf0, 0xca, 0xea, 0x60, 0x5b, 0xd6,
	0xfb, 0x56, 0x79, 0x5f, 0x44, 0x02, 0xad, 0x0a, 0x22, 0x19, 0x20, 0xa9, 0x97, 0xa8, 0x43, 0x21,
	0x4a, 0x85, 0xca, 0x40, 0xe4, 0xd8, 0x4f, 0xdd, 0x83, 0xd8, 0x67, 0x5d, 0x2e, 0x12, 0xfe, 0x16,
	0x7c, 0x0c, 0xbe, 0x00, 0x12, 0x23, 0x1b, 0x8c, 0x1d, 0x99, 0xac, 0x36, 0xdd, 0x32, 0xa1, 0x4c,
	0x8c, 0xc8, 0x77, 0x6e, 0x6c, 0x97, 0x14, 0x31, 0xb4, 0x53, 0xe2, 0xe7, 0xff, 0xdc, 0xcf, 0x8f,
	0xcf, 0xff, 0xbf, 0x0f, 0x3d, 0x74, 0x31, 0x3b, 0x9d, 0x8e, 0x1a, 0x36, 0xf1, 0x9a, 0xec, 0xd4,
	0xf2, 0x4f, 0x83, 0xa0, 0x19, 0x50, 0xe2, 0x35, 0x83, 0xb7, 0x6e, 0xd3, 0xb6, 0x3d, 0xcb, 0xa7,
	0x81, 0xdd, 0x04, 0x9f, 0x61, 0x16, 0x36, 0x02, 0x4a, 0x18, 0x91, 0x11, 0x2f, 0x7b, 0xc4, 0x81,
	0xf1, 0xd6, 0xfd, 0xcc, 0x72, 0x97, 0xb8, 0xa4, 0xc9, 0x5b, 0x46, 0xd3, 0x13, 0x7e, 0xc5, 0x2f,
	0xf8, 0x3f, 0xb1, 0x74, 0xab, 0xf1, 0xbb, 0xbb, 0x31, 0xec, 0x41, 0x7c, 0xb3, 0xf8, 0x57, 0xf4,
	0x1b, 0x5f, 0xca, 0x68, 0x7d, 0xdf, 0xa2, 0x8e, 0xfc, 0x0c, 0x15, 0x7b, 0xa6, 0x22, 0xe9, 0x52,
	0x7d, 0xb3, 0xfb, 0x60, 0x1e, 0x69, 0x45, 0xec, 0x2c, 0x22, 0x6d, 0xdb, 0x25, 0xd4, 0x6b, 0x19,
	0xfb, 0x64, 0x3c, 0xf5, 0xfc, 0x16, 0x76, 0xda, 0xfa, 0x20, 0x0c, 0xa0, 0x85, 0x7d, 0xd6, 0xd6,
	0x03, 0x8a, 0x3d, 0x8b, 0x86, 0x07, 0x10, 0x1a, 0xfd, 0x62, 0xcf, 0x94, 0x3b, 0xa8, 0x34, 0xc0,
	0x6c, 0x0c, 0x4a, 0x51, 0x97, 0xea, 0xd5, 0xee, 0xbd, 0x79, 0xa4, 0x95, 0x58, 0x5c, 0x58, 0x44,
	0x9a, 0x9a, 0xe3, 0xf0, 0x6a, 0x82, 0x62, 0xf0, 0x8e, 0x19, 0x7d, 0xb1, 0x52, 0x3e, 0x46, 0x35,
	0x13, 0x26, 0x36, 0xc5, 0x01, 0xc3, 0xc4, 0x57, 0xd6, 0x38, 0xe8, 0xf1, 0x3c, 0xd2, 0x6a, 0x4e,
	0x5a, 0x5e, 0x44, 0xda, 0x3f, 0x39, 0x5c, 0x46, 0xcb, 0x41, 0xb3, 0x2c, 0xf9, 0x05, 0xaa, 0x88,
	0xf6, 0x9e, 0xa9, 0xac, 0xf3, 0xa7, 0xdc, 0x9b, 0x47, 0x5a, 0xd5, 0xe6, 0xb5, 0x21, 0x7f, 0xd8,
	0x3c, 0x75, 0xa9, 0x24, 0xcc, 0x11, 0x76, 0xb1, 0xcf, 0x8c, 0xfe, 0x12, 0x23, 0x1f, 0x23, 0xd4,
	0x99, 0x4c, 0xb0, 0xeb, 0x83, 0x33, 0x20, 0x4a, 0x89, 0x43, 0x9f, 0xc4, 0xc3, 0x5a, 0x49, 0x75,
	0xc8, 0xc8, 0x2f, 0x7b, 0x98, 0xd1, 0xae, 0x81, 0x33, 0x30, 0xf9, 0x08, 0x55, 0xf7, 0x29, 0x58,
	0x0c, 0x9c, 0x6e, 0xa8, 0x94, 0x39, 0x39, 0xde, 0x06, 0x64, 0x8b, 0xe2, 0x70, 0x14, 0x2e, 0x22,
	0xed, 0xdf, 0xfc, 0xbc, 0x4b, 0xe9, 0x1a, 0x37, 0x25, 0xc9, 0x87, 0x68, 0xc3, 0x9c, 0x82, 0x69,
	0x31, 0x50, 0x36, 0x74, 0xa9, 0x5e, 0xdb, 0xd9, 0x6c, 0x24, 0x9e, 0x68, 0x0c, 0xb0, 0x07, 0xdd,
	0xed, 0x79, 0xa4, 0x55, 0x9c, 0x29, 0x0c, 0x1d, 0x8b, 0xc5, 0xaf, 0xed, 0xef, 0xfc, 0x3e, 0x27,
	0x82, 0xd1, 0xbf, 0xa2, 0xc8, 0x2f, 0x97, 0x73, 0x76, 0x98, 0x52, 0x59, 0x85, 0xfc, 0x3f, 0x3b,
	0xb6, 0xc5, 0x16, 0x91, 0xa6, 0xac, 0x1c, 0xdb, 0xca, 0x4c, 0xda, 0x61, 0x31, 0xf8, 0x28, 0x70,
	0x12, 0x70, 0xf5, 0x46, 0xf0, 0x54, 0xf4, 0xac, 0x02, 0xa7, 0x92, 0xd1, 0x4f, 0x59, 0x31, 0xd8,
	0x84, 0x31, 0x08, 0x30, 0xba, 0x11, 0xec, 0x88, 0x9e, 0x55, 0xe0, 0x54, 0x32, 0xfa, 0x29, 0xcb,
	0xf8, 0x58, 0x42, 0x65, 0xd1, 0x21, 0x1f, 0x66, 0xb2, 0xf4, 0x74, 0x99, 0xa5, 0xbd, 0x3f, 0xca,
	0x52, 0x5b, 0xb7, 0xa6, 0x8c, 0xf4, 0x7c, 0x9b, 0x82, 0x07, 0xf1, 0xeb, 0xbb, 0xa5, 0x68, 0x1d,
	0xa1, 0xea, 0x73, 0x4a, 0xde, 0x80, 0xcd, 0x7a, 0x26, 0x0f, 0x56, 0xe2, 0xa8, 0x40, 0x14, 0x45,
	0x02, 0xf2, 0x8e, 0x4a, 0xa5, 0xeb, 0x8e, 0x5a, 0x92, 0xe4, 0xd7, 0xa8, 0x14, 0x7f, 0x3e, 0x26,
	0xca, 0xba, 0xbe, 0x56, 0xaf, 0xed, 0xfc, 0xd5, 0x48, 0x3f, 0x5d, 0x8d, 0x58, 0xe8, 0x3e, 0x8a,
	0x67, 0xb5, 0xe3, 0x96, 0x45, 0xa4, 0xfd, 0x27, 0xf8, 0x27, 0x84, 0x02, 0x76, 0xfd, 0x03, 0x08,
	0x5b, 0x57, 0x61, 0x6a, 0xeb, 0x14, 0x4e, 0x80, 0x82, 0x6f, 0xc3, 0xa4, 0xd5, 0x33, 0x8d, 0xbe,
	0xc0, 0xe6, 0x83, 0x50, 0xba, 0xb5, 0x20, 0xe4, 0x7c, 0x5b, 0xbe, 0x2b, 0xdf, 0x6e, 0xdc, 0x95,
	0x6f, 0x2b, 0xb7, 0xe7, 0xdb, 0x2e, 0x9c, 0x5f, 0xa8, 0xd2, 0xf7, 0x0b, 0x55, 0xfa, 0x71, 0xa1,
	0x4a, 0x1f, 0x66, 0xaa, 0xf4, 0x69, 0xa6, 0x4a, 0x9f, 0x67, 0x6a, 0xe1, 0xeb, 0x4c, 0x95, 0xce,
	0x66, 0xaa, 0x74, 0x3e, 0x53, 0xa5, 0xf7, 0x97, 0x6a, 0xe1, 0xec, 0x52, 0x2d, 0x7c, 0xbb, 0x54,
	0x0b, 0xaf, 0x76, 0x6f, 0x3a, 0x63, 0x6c, 0xcf, 0x11, 0x27, 0x5a, 0x93, 0x42, 0x40, 0x26, 0x98,
	0x11, 0x1a, 0x26, 0x27, 0xdb, 0xa8, 0xcc, 0xcf, 0x9b, 0xdd, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x76, 0x3a, 0xcb, 0x0f, 0x07, 0x00, 0x00,
}

func (this *Card) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Card)
	if !ok {
		that2, ok := that.(Card)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Card")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Card but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Card but is not nil && this == nil")
	}
	if this.ID != that1.ID {
		return fmt.Errorf("ID this(%v) Not Equal that(%v)", this.ID, that1.ID)
	}
	if this.Title != that1.Title {
		return fmt.Errorf("Title this(%v) Not Equal that(%v)", this.Title, that1.Title)
	}
	if this.Description != that1.Description {
		return fmt.Errorf("Description this(%v) Not Equal that(%v)", this.Description, that1.Description)
	}
	if this.ColumnID != that1.ColumnID {
		return fmt.Errorf("ColumnID this(%v) Not Equal that(%v)", this.ColumnID, that1.ColumnID)
	}
	if this.AssignedTo != that1.AssignedTo {
		return fmt.Errorf("AssignedTo this(%v) Not Equal that(%v)", this.AssignedTo, that1.AssignedTo)
	}
	if this.CreatedBy != that1.CreatedBy {
		return fmt.Errorf("CreatedBy this(%v) Not Equal that(%v)", this.CreatedBy, that1.CreatedBy)
	}
	if !this.DueDate.Equal(that1.DueDate) {
		return fmt.Errorf("DueDate this(%v) Not Equal that(%v)", this.DueDate, that1.DueDate)
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return fmt.Errorf("CreatedAt this(%v) Not Equal that(%v)", this.CreatedAt, that1.CreatedAt)
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return fmt.Errorf("UpdatedAt this(%v) Not Equal that(%v)", this.UpdatedAt, that1.UpdatedAt)
	}
	if !this.DeletedAt.Equal(that1.DeletedAt) {
		return fmt.Errorf("DeletedAt this(%v) Not Equal that(%v)", this.DeletedAt, that1.DeletedAt)
	}
	return nil
}
func (this *Card) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Card)
	if !ok {
		that2, ok := that.(Card)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if this.ColumnID != that1.ColumnID {
		return false
	}
	if this.AssignedTo != that1.AssignedTo {
		return false
	}
	if this.CreatedBy != that1.CreatedBy {
		return false
	}
	if !this.DueDate.Equal(that1.DueDate) {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return false
	}
	if !this.DeletedAt.Equal(that1.DeletedAt) {
		return false
	}
	return true
}
func (this *Column) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Column)
	if !ok {
		that2, ok := that.(Column)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Column")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Column but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Column but is not nil && this == nil")
	}
	if this.ID != that1.ID {
		return fmt.Errorf("ID this(%v) Not Equal that(%v)", this.ID, that1.ID)
	}
	if this.Title != that1.Title {
		return fmt.Errorf("Title this(%v) Not Equal that(%v)", this.Title, that1.Title)
	}
	if this.ProjectID != that1.ProjectID {
		return fmt.Errorf("ProjectID this(%v) Not Equal that(%v)", this.ProjectID, that1.ProjectID)
	}
	if len(this.Cards) != len(that1.Cards) {
		return fmt.Errorf("Cards this(%v) Not Equal that(%v)", len(this.Cards), len(that1.Cards))
	}
	for i := range this.Cards {
		if !this.Cards[i].Equal(that1.Cards[i]) {
			return fmt.Errorf("Cards this[%v](%v) Not Equal that[%v](%v)", i, this.Cards[i], i, that1.Cards[i])
		}
	}
	if this.CreatedBy != that1.CreatedBy {
		return fmt.Errorf("CreatedBy this(%v) Not Equal that(%v)", this.CreatedBy, that1.CreatedBy)
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return fmt.Errorf("CreatedAt this(%v) Not Equal that(%v)", this.CreatedAt, that1.CreatedAt)
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return fmt.Errorf("UpdatedAt this(%v) Not Equal that(%v)", this.UpdatedAt, that1.UpdatedAt)
	}
	if !this.DeletedAt.Equal(that1.DeletedAt) {
		return fmt.Errorf("DeletedAt this(%v) Not Equal that(%v)", this.DeletedAt, that1.DeletedAt)
	}
	return nil
}
func (this *Column) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Column)
	if !ok {
		that2, ok := that.(Column)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.ProjectID != that1.ProjectID {
		return false
	}
	if len(this.Cards) != len(that1.Cards) {
		return false
	}
	for i := range this.Cards {
		if !this.Cards[i].Equal(that1.Cards[i]) {
			return false
		}
	}
	if this.CreatedBy != that1.CreatedBy {
		return false
	}
	if !this.CreatedAt.Equal(that1.CreatedAt) {
		return false
	}
	if !this.UpdatedAt.Equal(that1.UpdatedAt) {
		return false
	}
	if !this.DeletedAt.Equal(that1.DeletedAt) {
		return false
	}
	return true
}
func (this *Card) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&entity.Card{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Title: "+fmt.Sprintf("%#v", this.Title)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	s = append(s, "ColumnID: "+fmt.Sprintf("%#v", this.ColumnID)+",\n")
	s = append(s, "AssignedTo: "+fmt.Sprintf("%#v", this.AssignedTo)+",\n")
	s = append(s, "CreatedBy: "+fmt.Sprintf("%#v", this.CreatedBy)+",\n")
	if this.DueDate != nil {
		s = append(s, "DueDate: "+fmt.Sprintf("%#v", this.DueDate)+",\n")
	}
	if this.CreatedAt != nil {
		s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	}
	if this.UpdatedAt != nil {
		s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	}
	if this.DeletedAt != nil {
		s = append(s, "DeletedAt: "+fmt.Sprintf("%#v", this.DeletedAt)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Column) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&entity.Column{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Title: "+fmt.Sprintf("%#v", this.Title)+",\n")
	s = append(s, "ProjectID: "+fmt.Sprintf("%#v", this.ProjectID)+",\n")
	if this.Cards != nil {
		s = append(s, "Cards: "+fmt.Sprintf("%#v", this.Cards)+",\n")
	}
	s = append(s, "CreatedBy: "+fmt.Sprintf("%#v", this.CreatedBy)+",\n")
	if this.CreatedAt != nil {
		s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	}
	if this.UpdatedAt != nil {
		s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	}
	if this.DeletedAt != nil {
		s = append(s, "DeletedAt: "+fmt.Sprintf("%#v", this.DeletedAt)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringEntity(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Card) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Card) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Card) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeletedAt != nil {
		{
			size, err := m.DeletedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.UpdatedAt != nil {
		{
			size, err := m.UpdatedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.CreatedAt != nil {
		{
			size, err := m.CreatedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.DueDate != nil {
		{
			size, err := m.DueDate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.CreatedBy != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.CreatedBy))
		i--
		dAtA[i] = 0x30
	}
	if m.AssignedTo != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.AssignedTo))
		i--
		dAtA[i] = 0x28
	}
	if m.ColumnID != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.ColumnID))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Column) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Column) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Column) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeletedAt != nil {
		{
			size, err := m.DeletedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.UpdatedAt != nil {
		{
			size, err := m.UpdatedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.CreatedAt != nil {
		{
			size, err := m.CreatedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEntity(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.CreatedBy != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.CreatedBy))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Cards) > 0 {
		for iNdEx := len(m.Cards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Cards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEntity(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ProjectID != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.ProjectID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEntity(dAtA []byte, offset int, v uint64) int {
	offset -= sovEntity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedCard(r randyEntity, easy bool) *Card {
	this := &Card{}
	this.ID = uint32(r.Uint32())
	this.Title = string(randStringEntity(r))
	this.Description = string(randStringEntity(r))
	this.ColumnID = uint32(r.Uint32())
	this.AssignedTo = uint32(r.Uint32())
	this.CreatedBy = uint32(r.Uint32())
	if r.Intn(5) != 0 {
		this.DueDate = timerpc.NewPopulatedTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.CreatedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.UpdatedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.DeletedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedColumn(r randyEntity, easy bool) *Column {
	this := &Column{}
	this.ID = uint32(r.Uint32())
	this.Title = string(randStringEntity(r))
	this.ProjectID = uint32(r.Uint32())
	if r.Intn(5) != 0 {
		v1 := r.Intn(5)
		this.Cards = make([]*Card, v1)
		for i := 0; i < v1; i++ {
			this.Cards[i] = NewPopulatedCard(r, easy)
		}
	}
	this.CreatedBy = uint32(r.Uint32())
	if r.Intn(5) != 0 {
		this.CreatedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.UpdatedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if r.Intn(5) != 0 {
		this.DeletedAt = timerpc.NewPopulatedTime(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyEntity interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneEntity(r randyEntity) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringEntity(r randyEntity) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneEntity(r)
	}
	return string(tmps)
}
func randUnrecognizedEntity(r randyEntity, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldEntity(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldEntity(dAtA []byte, r randyEntity, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateEntity(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Card) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovEntity(uint64(m.ID))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.ColumnID != 0 {
		n += 1 + sovEntity(uint64(m.ColumnID))
	}
	if m.AssignedTo != 0 {
		n += 1 + sovEntity(uint64(m.AssignedTo))
	}
	if m.CreatedBy != 0 {
		n += 1 + sovEntity(uint64(m.CreatedBy))
	}
	if m.DueDate != nil {
		l = m.DueDate.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.CreatedAt != nil {
		l = m.CreatedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = m.UpdatedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.DeletedAt != nil {
		l = m.DeletedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	return n
}

func (m *Column) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovEntity(uint64(m.ID))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.ProjectID != 0 {
		n += 1 + sovEntity(uint64(m.ProjectID))
	}
	if len(m.Cards) > 0 {
		for _, e := range m.Cards {
			l = e.Size()
			n += 1 + l + sovEntity(uint64(l))
		}
	}
	if m.CreatedBy != 0 {
		n += 1 + sovEntity(uint64(m.CreatedBy))
	}
	if m.CreatedAt != nil {
		l = m.CreatedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = m.UpdatedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.DeletedAt != nil {
		l = m.DeletedAt.Size()
		n += 1 + l + sovEntity(uint64(l))
	}
	return n
}

func sovEntity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEntity(x uint64) (n int) {
	return sovEntity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Card) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Card: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Card: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnID", wireType)
			}
			m.ColumnID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ColumnID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssignedTo", wireType)
			}
			m.AssignedTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssignedTo |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			m.CreatedBy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedBy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DueDate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DueDate == nil {
				m.DueDate = &timerpc.Time{}
			}
			if err := m.DueDate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &timerpc.Time{}
			}
			if err := m.CreatedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &timerpc.Time{}
			}
			if err := m.UpdatedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = &timerpc.Time{}
			}
			if err := m.DeletedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Column) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Column: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Column: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectID", wireType)
			}
			m.ProjectID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cards = append(m.Cards, &Card{})
			if err := m.Cards[len(m.Cards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			m.CreatedBy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedBy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = &timerpc.Time{}
			}
			if err := m.CreatedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = &timerpc.Time{}
			}
			if err := m.UpdatedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = &timerpc.Time{}
			}
			if err := m.DeletedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEntity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEntity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEntity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEntity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEntity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEntity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEntity = fmt.Errorf("proto: unexpected end of group")
)
