# Page settings
baseurl = "localhost:1313"
title = "Focalboard"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Focalboard"
    home = "Home"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/contribute/"
      name = "Contribute"
      weight = 10

  # Hero section
  [params.hero]
    title = "Get Focalboard"
    subtitle = ''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Contribute"
    description = "Join the hunrdeds of contributors and submit code directly to the Focalboard open-source project."
    url = "/contribute/"
    button = "Start Contributing"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Integrate"
    description = "Integrate with Mattermsot through incoming and outgoing webhooks, slash commands, OAuth 2.0 and the REST API."
    url = "/integrate"
    button = "Start Integrating"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Extend"
    description = "Extend Focalboard to fit your purposes."
    url = "#"
    button = "Start Extending"
    icon = "icon-rocket"
    img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"

  # Footer section
  [params.footer]
    enable = true
    twitter = 'https://twitter.com/mattermost'
    facebook = 'https://www.facebook.com/Mattermost-2300985916642531/'
    youtube = 'https://www.youtube.com/channel/UCNR05H72hi692y01bWaFXNA'
    copyright = '&copy; Mattermost, Inc. All Rights Reserved.'
