database:
  host: "127.0.0.1"
  port: "5432"
  user: "thanhpp"
  pass: "testthanhpp"
  name: "promuser"
  log: "INFO"

log:
  level: "DEBUG"
  color: true

grpc:
  publichost: "0.0.0.0"
  port: "8090"
  maxconnections: 100