servicename: "portal"
environment: "development"

log:
  level: "DEBUG"
  color: true

etcd:
  endpoints:
    - "127.0.0.1:2379"
  timeout: 10

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

webserver:
  host: "127.0.0.1"
  port: "12345"
